function (add_subdirectory_if_exist SubDir)
	if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${SubDir}/CMakeLists.txt")
		add_subdirectory(${SubDir})
	endif()
endfunction()

function (find_package_from_conan_V1)
	set(i 0)
	foreach(loop ${ARGV})
		set_package_root_postfix(${loop} ${loop}_DIR /cmake)
		find_package(${loop} REQUIRED CONFIG)
		math(EXPR i "${i} + 1")
	endforeach()
endfunction()
